# C++ options
CXX := g++
CXXFLAGS := -Wall -Wextra -Werror -std=c++20

# Target for C++ program
listing2: ./listing-2-02/main.cpp
	$(CXX) $(CXXFLAGS) -o ./listing-2-02/$@ $<

listing4: ./listing-2-04/main.cpp
	$(CXX) $(CXXFLAGS) -o ./listing-2-04/$@ $<

listing6: ./listing-2-06/main.cpp
	$(CXX) $(CXXFLAGS) -o ./listing-2-06/$@ $<

listing8: ./listing-2-08/main.cpp
	$(CXX) $(CXXFLAGS) -o ./listing-2-08/$@ $<

listing9: ./listing-2-09/main.cpp
	$(CXX) $(CXXFLAGS) -o ./listing-2-09/$@ $<

listing11: ./listing-2-11/main.cpp
	$(CXX) $(CXXFLAGS) -o ./listing-2-11/$@ $<

listing14: ./listing-2-14/main.cpp
	$(CXX) $(CXXFLAGS) -o ./listing-2-14/$@ $<

listing15: ./listing-2-15/main.cpp
	$(CXX) $(CXXFLAGS) -o ./listing-2-15/$@ $<

listing16: ./listing-2-16/main.cpp
	$(CXX) $(CXXFLAGS) -o ./listing-2-16/$@ $<

listing34: ./listing-2-34/main.cpp
	$(CXX) $(CXXFLAGS) -o ./listing-2-34/$@ $<
